tasks:
  - name: Install Dependencies & Start
    init: npm install
    command: npm run dev

ports:
  - name: Slides Preview
    description: Port 3030 for the slides
    port: 3030
    onOpen: open-browser
