name: GitHub Pages

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**/README.md'

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          cache: npm
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright
        run: npx playwright install --with-deps

      - name: Install slidev
        run: npm i -g @slidev/cli @slidev/theme-default @iconify-json/ci @iconify-json/fa6-solid @iconify-json/octicon

      - name: Add Umami script
        run: touch index.html && node umami.js
        env:
          UMAMI_WEBSITE_ID: ${{ vars.UMAMI_WEBSITE_ID }}

      - name: Build
        run: |
          slidev build --base /${{ github.event.repository.name }}/
          /bin/ls pages | while read line ; do cp "$PWD/pages/$line/$line.md" slides_tmp.md && slidev build slides_tmp.md --base "/${{ github.event.repository.name }}/$line" -o "./dist/$line" && rm slides_tmp.md ; done

      - uses: actions/configure-pages@v3

      - uses: actions/upload-pages-artifact@v1
        with:
          path: dist

      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v2
